### ISSUE TITLE
Feature request: automatically building for many platforms and uploading a release with assets to Github

### ISSUE THREAD

**Issue by vi** [sunng87/cargo-release#122]
Maybe apart of platforms there also should be feature sets, maybe there should also be [cross](https://github.com/rust-embedded/cross) support.

**Comment by epage** [comment]
Could you help me understand where the value is in having this baked into `cargo-release` rather than people doing this within their CIs, conditioned on the tag that `cargo-release` creates?

Supporting this is quite a complicated thing
- Building for all relevant platforms, including Windows and Mac
- Having the right policy for bundling assets
- Baking in github-specific logic.

I have been wanting to streamline the asset distribution workflow but haven't been getting time  to devote to it.  One example is the idea of [cargo-tarball](https://github.com/crate-ci/cargo-tarball) for allowing people to describe the policy of how they want assets bundled.

**Comment by vi** [comment]
> Could you help me understand where the value is in having this baked into cargo-release rather than people doing this within their CIs, conditioned on the tag that cargo-release creates?

To allow creating releases for small projects, where just cross-compiling everything is easier than setting up all those CIs.

> Baking in github-specific logic.

I assumed there is already some, to provide Github releases with appropriate chanelog chunk inside a release bodies.

**Comment by epage** [comment]
Due to the amount of policy (as described in my earlier post), I'm going to go ahead and say this is out of scope in an effort to clean up our issues.  If @sunng87 or someone else disagrees, feel free to re-open.

Creating a CI with github releases isn't too bad.  You can see an [example from one of my bins](https://github.com/crate-ci/committed/blob/master/azure-pipelines.yml)

> I assumed there is already some, to provide Github releases with appropriate chanelog chunk inside a release bodies.

Actually we don't.
