### ISSUE TITLE
Update crates only if they changed

### ISSUE THREAD

**Issue by emschwartz** [sunng87/cargo-release#143]
Does (or could) `cargo release` check whether files have been changed since the last release before tagging a new version?

I have a workspace with a bunch of different crates that depend on one another. It would be nice if this tool would tag and release new versions of the sub-crates only when they've actually changed since the last time they were released.

Also, thank you for your work on this project!

**Comment by epage** [comment]
This would be ideal though I have some concerns about it
- How do we identify the previous tag version? Currently, we use templates to generate the tags which complicates sorting them.
- Is it safe to only look at changed files in a crate's directory?
  - What if the change came about in another crate that does code-gen, like macros?  I recently changed a crate with traits and the derive crate for the traits but I still needed to release the crate that uses the derive macro.
  - What about files that aren't relevant, like online documentation?  I guess we could use Cargo.toml's [`exclude`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields-optional) for that.

**Comment by emschwartz** [comment]
Thanks for the quick response!

> How do we identify the previous tag version? Currently, we use templates to generate the tags which complicates sorting them.

How about:
1. Use the same method from `version.rs` to determine the current version but don't increment the version
2. Append the tag (if there is one) to figure out the pre-bump tag we'd expect
3. Check if that tag exists in the git history
4. If the tag exists, run `git diff` to determine whether anything in the `src` or `Cargo.toml` has changed

> Is it safe to only look at changed files in a crate's directory? 

Good question. Dependency changes should be captured in changes to the `Cargo.toml` file, no?

> What about files that aren't relevant, like online documentation? I guess we could use Cargo.toml's exclude for that.

:+1:

**Comment by epage** [comment]
> Use the same method from version.rs to determine the current version but don't increment the version

That will work in the majority case.  We do need to add support to cargo-release for bumping the pre-release version (make it easy for someone to go from 1.1.0.dev10 to 2.0.0.dev0 when introducing a breaking change).  This should be corner case enough that we just error out if the tag was not found.  Granted, that will cause a `Cargo.toml` change.

> Good question. Dependency changes should be captured in changes to the Cargo.toml file, no?

If it is all within the workspace like with my example I gave, the dependency change happens when we decide to release the top-level crate that is changed by one of its dependencies.

We could say that we won't solve this problem and people should know the impact of it all, run `--dry-run` first to see what we're guessing we should do, and then they should do `--package` to opt-in the crate that we didn't detect changes for.  However through my experience with the different tools I've written, I've also found that when you start making decisions on the user's behalf, they stop thinking about the decision, trusting in the tool (too much).  I've also found people too often run tools without first using `--dry-run` and really looking at its output.

We could detect and warn when a crate is being released that doesn't have changes, telling the user they can use the `--exclude` flag to not release it.  This makes the defaults "safe" while getting closer to the behavior you're asking for.

**Comment by emschwartz** [comment]
I agree that no one is going to carefully inspect the output of `--dry-run`. I glanced through it before using this tool the first time but with 10+ crates in the workspace, the list of steps is pretty long so I'm definitely less likely to do it again.

> We could detect and warn when a crate is being released that doesn't have changes, telling the user they can use the --exclude flag to not release it. This makes the defaults "safe" while getting closer to the behavior you're asking for.

Something like that sounds great to me. Would you warn while the release process is going (like in the confirmation step) or only in the dry run?

**Comment by epage** [comment]
> I agree that no one is going to carefully inspect the output of --dry-run. I glanced through it before using this tool the first time but with 10+ crates in the workspace, the list of steps is pretty long so I'm definitely less likely to do it again.

Yeah, something we can improve.  In part via https://github.com/sunng87/cargo-release/issues/138 and in part by looking into switching to logging so people can get different degrees of information.

> Something like that sounds great to me. Would you warn while the release process is going (like in the confirmation step) or only in the dry run?

No sure if I have an opinion on this yet.  Might be good to see what aligns with the code.
