### ISSUE TITLE
Support custom publish script

### ISSUE THREAD

**Issue by jstoneham** [sunng87/cargo-release#178]
We use Cloudsmith to publish our private crates to. It would be pretty nice to supply a script that could stand in place of the `cargo publish` step to kick off the Cloudsmith push, since they don't support `cargo publish` yet.

**Comment by epage** [comment]
The hard thing about maintaining a project is deciding when to say "no".  I worry that this level of customization is going too far especially for something that would ideally be shortlived.

However, an alternative approach is that you can develop an [`xtask`](https://github.com/matklad/cargo-xtask) for this.  We could take pieces of `cargo-release` and turn them into a library you can call so you can reuse some of our logic.

Two caveats
- Feel free to make a case otherwise
- I'm just a contributor and @sunng87 is fully welcome to say otherwise.

**Comment by jstoneham** [comment]
Yeah, I definitely understand. It /does/ feel like different organizations might want to do different/additional things at publish time, though - we have a pre-release hook, why not a post-release hook?

**Comment by epage** [comment]
I think the hook is meant for updating changelogs and the like and are a challenge to support cross platform. If other cases come up for post-release hooks, maybe itll make sense but I feel like xtasks are the way to go.

**Comment by igalic** [comment]
> If other cases come up for post-release hooks, maybe itll make sense but I feel like xtasks are the way to go.

we'd like to create issues or PRs in downstream repos that package our software
a simple script, analogous to `pre-release-hook`, using the [github cli](https://cli.github.com/manual/) may be enough to do so
