### ISSUE TITLE
Bumping to dev version after release makes testing PR's more complicated

### ISSUE THREAD

**Issue by timfish** [sunng87/cargo-release#199]
I created a PR for `libffi-sys` which uses the `cargo-release` workflow. It is difficult to test this PR because the version in master does not match the version that you need to patch.

The standard way to test a PR for `libffi-sys` with `libffi` would be to patch using the PR branch:
```
[dependencies]
libffi = "0.9.0"

[patch.crates-io]
libffi-sys = { git = "https://github.com/timfish/libffi-sys-rs.git", branch = "msvc-build" }
```
However, this wont work because `[patch]` requires that the versions match. PRs are almost always based of master (`0.9.1-alpha.0` in this case) and the version being patched is the last release (`0.9.0`) so you'll get an error:
```
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  patch for `libffi-sys` in `https://github.com/rust-lang/crates.io-index` did not resolve to any crates.
```
I can certainly see how bumping to a dev version after release can be useful, but it makes testing PRs more complicated. I've been getting around this by branching off the PR and reverting the version number but this makes contributing to libraries using `cargo-release` a little bit more complicated.

Maybe the last two steps in the workflow could be optional? Then library authors can choose between the two workflows depending on whether their crate has a lot out outside contributors?
```
5. Bump version for next development cycle
6. git push
```

**Comment by epage** [comment]
> I can certainly see how bumping to a dev version after release can be useful, but it makes testing PRs more complicated. 

I'm curious about this workflow.  It seems you have two coupled crates that need to be tested in lockstep but you don't have them in the same repo?  How come?

> Maybe the last two steps in the workflow could be optional?

They are optional.  See `--no-dev-version` and `no-dev-version = true` in https://github.com/sunng87/cargo-release/blob/master/docs/reference.md#config-fields

I use this on all of my crates because I've just not taken the time to experiment with the `dev-version-ext` workflow.

Related issues:
- https://github.com/sunng87/cargo-release/issues/82 seems to be more about the development workflow.
- #132 is for workspaces

**Comment by timfish** [comment]
Thanks for the quick response! Sorry, this does appear to be a dupe of #82 

> I'm curious about this workflow. It seems you have two coupled crates that need to be tested in lockstep but you don't have them in the same repo? How come?

No idea as I'm not the maintainer. Maybe some historical reasons?
