### ISSUE TITLE
The system for detecting previous changes is silly

### ISSUE THREAD

**Issue by Lokathor** [sunng87/cargo-release#200]
Every time i release a new version of something i seem to be getting a message like

```
[2020-01-08T21:45:21Z INFO ] Cannot detect changes for wide because tag v0.4.3-alpha.0 is missing. Try setting `--prev-tag-name <TAG>`.
```

But I'm using _exclusively_ this tool to do my releases so it's silly that it can't keep track of its own tag naming scheme. It [seems to just be a tag for each version](https://github.com/Lokathor/wide/releases), which is pretty easy to understand. However, it also updates the version stored with an `-alpha.0` when a new version is released, and that's where things go wrong.

What happens is that you're working on `0.4.2-alpha.0`, then you release that, and the tool releases it as `0.4.2` with a git tag to match and bumps your version in the repo to `0.4.3-alpha.0`. Then when you go to release that version, it doesn't see a tag for `0.4.3-alpha.0` because the last tag was `0.4.2`, and then it says it can't detect changes.

Checking for the current version's tag first is fine, but if that's not found just automatically go back through the tag list to find the latest tag version and compare to that. Or just don't even auto-compare at all. But the current confluence of systems makes it so that just using the tool in the default mode makes it print error messages about problems that it gave itself, which is silly.

**Comment by epage** [comment]
> But the current confluence of systems makes it so that just using the tool in the default mode makes it print error messages about problems that it gave itself, which is silly.

Could you clarify the problem you are running into.  The tool should still work when the message is given.
- Is the message too alarmist?
- Is the message confusing or unclear?
- Is something else going on?

Better understanding the user impact will be important for deciding how to move forward. 

One thing I suspect we can immediately do is to limit the message to workspaces since the value is greatly diminished for individual crates and I suspect most users will be using individual crates.

> Checking for the current version's tag first is fine, but if that's not found just automatically go back through the tag list to find the latest tag version and compare to that.

The question is how do we find the previous tag?  The user defines the tag format.  If we defined the tag format, we could parse the tags, sort the version, and be done.  Since we do not have that control, we could hack something together but it will be messy, brittle, and might no longer work if we make some other changes (partially evaluating the template and splitting the tags according to a special parsing of that would fail if we switched to a proper template language).

> Or just don't even auto-compare at all.

Are you saying the feature should be removed?  It was added because people wanted requested it.  We've not gotten too much feedback from others but I know I've been finding it useful.  Granted, I've not migrated my workflow to using post-release version bumps (ie I have `no-dev-version` set) so the auto-detection works for me.

As-is, the message is just telling you how you can be opting into the feature.  If you don't care, you can merrily go along your way.  If you do care, you can re-run with that flag set. So I'm unclear on why we'd completely remove it.

We could not print the message but then people might read into nothing being printed.

**Comment by Lokathor** [comment]
Well the only things I ever type using cargo-release are `cargo release --dry-run` and `cargo release`. I don't pick any other command line options at all. I don't specify a tag, I don't specify an automatic version bump, or anything. Everything that cargo-release is doing is just "the default".

So my thesis is basically, since I'm not picking any options at all, whatever the default option combination ends up being when you pick nothing should not end up showing a warning message about something being wrong.

> The user defines the tag format.

I have never written a tag format or even told cargo-release to make tags or check tags. There must be some sort of default format somewhere. It seems to just be "v{crate version}".

> Are you saying the feature should be removed?

No, I'm sure it really is useful to people. I don't want the diff feature removed entirely.

However, if I didn't ask for a comparison with a specific version and the tool decides on its own to do an automatic comparison anyway, then it should either try harder to look through the past version tags, OR it should stay quiet when it can't find a version (since I didn't ask for a comparison anyway).

**Comment by sunng87** [comment]
I find the compare system a little inconsistent with our defaults. Because by default, `cargo-release` bumps version to a dev one after release, so next time user will get this message. 

I suggest to change to message level to `debug` before we come up with a solution for default case.
