### ISSUE TITLE
Run clippy before creating a release

### ISSUE THREAD

**Issue by tversteeg** [sunng87/cargo-release#211]
I tend to run `cargo release` while forgetting to run clippy before that. It would be nice if there would be an option that automatically runs `cargo clippy --all-targets --all-features -- -D clippy::all` and won't proceed with releasing if that fails.

**Comment by epage** [comment]
Could you help me understand why this wouldn't be done in CI and why that wouldn't be sufficient?  That is where I run clippy for my projects and I only release stuff that has gone through CI.

If we do move forward with it, my biggest concern is that this is one implementation of validation and each project probably has its own form of pre-release validation that would be wanted.  It seems like it'd be best to either
- Use the [pre-release hook](https://github.com/sunng87/cargo-release/blob/master/docs/reference.md#config-fields) for this
- Use cargo-just to orchestrate clippy and release
- Create a [cargo xtask](https://github.com/matklad/cargo-xtask) for this.

**Comment by epage** [comment]
> I do have it as part of my CI, but the problem with that is that if I do a release with cargo release and then the CI fails because clippy didn't pass I also won't get release artifacts.

If clippy is running in CI, how does this happen?

> Of course this problem could be solved on my end but running clippy seems like something so common that it might be worth including.

Does everyone want clippy configured the same though?  You specified ` -D clippy::all` but I don't think I have that set.    Or of its based on need, aren't tests more important than clippy?  For me personally, I wouldn't run it because I have clippy in the CI and don't want releasing to be any slower.  So my concern isn't with your use case, which is a reasonable one, but with the explosion of permutations we'd need to support.  This is sounding more like its better suited by a extensible workflow automation tool which I listed three classes of options I'm familiar with.

**Comment by jyn514** [comment]
> > I do have it as part of my CI, but the problem with that is that if I do a release with cargo release and then the CI fails because clippy didn't pass I also won't get release artifacts.

> If clippy is running in CI, how does this happen?

Not the OP, but this can happen to any project without [bors](https://bors.tech/essay/2017/02/02/pitch/), or even a project with bors if clippy releases a new version between the last CI run and a release.
