### ISSUE TITLE
cargo release --dry-run does not run cargo publish --dry-run

### ISSUE THREAD

**Issue by saethlin** [sunng87/cargo-release#215]
If a crate builds but is rejected by `cargo publish` for whatever reason (such as having a path dependency), the release process aborts partway through, possibly publishing one but not all components of a workspace.

`cargo publish --dry-run` detects such problems, but it looks like that isn't run by `cargo release --dry-run`. It probably should be.

**Comment by epage** [comment]
I noticed this as well and considered it.  The main reason I never went and implemented it is that I was concerned that it might fail since we haven't done any of the other steps.

For example, if your crate's current version is uploaded and you do `cargo release patch --dry-run`, `cargo publish --dry-run` will be performed on an existing version.  Will it fail?
