### ISSUE TITLE
Release only specified workspace crates

### ISSUE THREAD

**Issue by dignifiedquire** [sunng87/cargo-release#236]
I have some crates in my workspace that do not regularly change, and I would like to skip those when publishing releases for the ones that do have changes. It would be great if I could filter the crates to be released on fly by sth like this

```
$ cargo release --packages foo,bar,baz minor
```

**Comment by epage** [comment]
`cargo-release` should support `--package`, `--exclude`, and `--all` in a way similar to built-in cargo commands.  Could you give that a try to see if it works to fit your needs?

**Comment by dignifiedquire** [comment]
oh, great I did not realize that, will try it out and report back

**Comment by dignifiedquire** [comment]
Running 

```
$ cargo release --package foo --dry-run patch
[2020-11-10T13:07:19Z INFO ] Update foo to version 1.0.1
[2020-11-10T13:07:19Z INFO ] Update bar to version 1.0.1
[2020-11-10T13:07:19Z INFO ] Update baz to version 1.0.1
[2020-11-10T13:07:19Z INFO ] Running cargo publish on foo
[2020-11-10T13:07:19Z INFO ] Running cargo publish on bar
[2020-11-10T13:07:19Z INFO ] Running cargo publish on baz
...
```

so it does not seem to exclude the others

**Comment by dignifiedquire** [comment]
I am using version `0.13.8`

**Comment by epage** [comment]
(sorry for the long delay)

Does your workspace root have no crate associated with it?  When this is the case, [clap-cargo selects all packages](https://github.com/crate-ci/clap-cargo/blob/master/src/workspace.rs#L40), even if you specify `--package`.  You can only use `--exclude` in this case.

If this is not what `cargo check` and friends do, then I'm all for changing it to better match cargo.

**Comment by dignifiedquire** [comment]
Ah yes, there is no root crate, I guess this matches that behaviour you are describing then.

**Comment by steveeJ** [comment]
Regardless of how builtin cargo commands behave it seems counter-intuitive that there is no inclusive-mode in a virtual workspace. Building an exhaustive list for `--exclude` seems cumbersome and fragile. Cumbersome because it needs to be known prior to calling `cargo release` which defeats some of its convenience. Fragile because the list can be incomplete and accidentally trigger unwanted releases.

I would like to discuss adding a flag to `cargo release` to turn on inclusive mode for virtual workspaces.

A very simple solution could be adding a boolean CLI flag which triggers the same condition as if the workspace had a toplevel crate.
Even simpler could be to enable it implicitly whenever `--package` is provided.
I haven't fully thought this through but I happily will if there is willingness of getting such a feature in.

**Comment by epage** [comment]
I've dug into cargo some and confirmed we are deviating/  A fix is up coming

**Comment by epage** [comment]
#290 resolved this (linked the wrong one)
