### ISSUE TITLE
Allow pre-release replacements to be specified relative to the project root

### ISSUE THREAD

**Issue by Michael-F-Bryan** [sunng87/cargo-release#283]
I have a project with `CHANGELOG.md` at the root of the repository and sub-crates in nested directories and would like to use pre-release replacements [to update links in `CHANGELOG.md`](https://github.com/sunng87/cargo-release/blob/master/docs/faq.md#maintaining-changelog).

My directory structure:
- /
  - CHANGELOG.md
  - Cargo.toml
  - release.toml
  - crates/
    - first-crate/
    - second-crate/

My `release.toml`:
```toml
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/assert-rs/predicates-rs/compare/{{tag_name}}...HEAD", exactly=1},
]
```

Whenever I run `cargo release` on this workspace it'll complain that `crates/first-crate/CHANGELOG.md` doesn't exist because each replacement is resolved relative to the crate being released. In this case I can't use `../CHANGELOG.md` as the path because there are crates at different levels.

Is it possible to use something like `file="/CHANGELOG.md"` to make the replacement relative to the repository's root directory (i.e. the path printed by `git rev-parse --show-toplevel`)?

**Comment by epage** [comment]
`cargo-release` is running pre-release replacements for every crate's release.  I'm assuming just allowing workspace-relative paths wouldn't help fix that because you wouldn't want to update the file multiple times.

We have this covered in the [FAQ](https://github.com/sunng87/cargo-release/blob/master/docs/faq.md#how-do-i-apply-a-setting-only-to-one-crate-in-my-workspace) though maybe it could be made clearer.

`/release.toml` is inherited by all of the crates in a workspace.  What you most likely need is to set a setting that *isn't* inherited.  The per-crate way of specifying config is by setting it in your `Cargo.toml` ([example](https://github.com/crate-ci/typos/blob/master/Cargo.toml#L33))

**Comment by epage** [comment]
Considering
- The proposal would likely lead to broken projects (updating files when they shouldn't be)
- There seems to be a path forward
- There haven't been any updates

I'm going to go ahead and close this.  Feel free to let me know if we missed something

**Comment by xldenis** [comment]
Hi, 

I'm having the same issue, and while I've seen the proposed solution (adding a dummy hook to every crate), this kind of sucks in a project with over a dozen (and growing) crates. Additionally, its a virtual workspace so no root crate to act as flag bearer. 

I'm working around it currently by adding:

```
[package.metadata]
pre-release-replacements = [ ]
```
to each `Cargo.toml`, but honestly, a proper "workspace only" setting would be good.
