### ISSUE TITLE
invisible text on Konsole solarized light theme

### ISSUE THREAD

**Issue by goertzenator** [sunng87/cargo-release#41]
Some of the text output is invisible when using KDE Konsole with the solarized light theme.  Having not used this program in some time, I initially thought `cargo release` was just hanging, but eventually figured out what was going on.

I haven't had this issue with any other programs, so perhaps the use of color should be revisited for this program.

![image](https://user-images.githubusercontent.com/605072/34468630-b5ebafc2-eed2-11e7-87d0-dc4c5606d08a.png)

**Comment by lunaryorn** [comment]
The same issue occurs in iTerm2 with Solarized Light.

`cargo release` prints the confirmation prompt in white color which is the same as the background colour in Konsole and iTerm2 implementations of Solarized Light.  

If you switch to Solarized Dark, or select the area with the mouse, the text becomes visible.

@sunng87 Can you perhaps add a flag to disable colours for this prompt?  Or use bold text instead of a specific colour?

**Comment by sunng87** [comment]
Hi @goertzenator @lunaryorn , this should be fixed in beta4, in which I removed color `White` for the prompt text.

**Comment by lunaryorn** [comment]
@sunng87 Many thanks for the quick fix ❤️
