### ISSUE TITLE
option to git push just after tagging

### ISSUE THREAD

**Issue by davidB** [sunng87/cargo-release#90]
Hi,

Nice plugin.

I have CI (travis, Azure) that trigger some steps (build app + zip and upload to repository / github releases) only if the current bug is on a tag.
But cargo-release git push after the bump version. So the build of the released version (and its deployment) is not triggered and done.

Do you plan this features (or accept PR) to do it ?

As I workaround, I though to redo the workflow of cargo-release with few tasks in cargo-make (I already use cargo-make to drive ci tasks, and call/wrap cargo-release). My wip project: https://github.com/ffizer/ffizer/

**Comment by epage** [comment]
Tangent: for azure, I recommend checking out the conversations going on in the issues over at [crate-ci](https://github.com/crate-ci/resources/issues).  We're looking at simplifying some of the workflow.

So let me see if I understand.  When pushing multiple commits and tags to github, both Travis and Azure only trigger a build on the last event.  So if you trigger off of commits and tags, it will not do a separate build run for the latest commit and latest tag but instead do a single build run and not tell you its for a tag?

For Travis, I thought I've seen dedicated tag builds but I could be mistaken.  I wouldn't be surprised if Azure has problems with this.

I don't know about @sunng87 but it seems reasonable to help with this though I am curious about other possible routes, including:

- Talking with the Azure guys.  They seem really open.
- Having a separate pipeline that only triggers on tag.  Maybe this would work?
  - I've already been considering this workflow to cut to speed up my CI since there isn't need for validation on a new release if all previous commits went through validation.

**Comment by davidB** [comment]
I redid a test and got a different behavior, I'll investigate (maybe I did a mistake :-P ). I'll keep you informed

**Comment by epage** [comment]
Going to go ahead and close this.  If you come across it again, you are welcome to re-open it.
